name: Run JUnit tests
on: pull_request

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Do nothing
              run: exit 0
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Do nothing
              run: exit 0
